# Generated by Django 5.2 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_historicaltv_rewatch_since_tv_rewatch_since"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltv",
            name="rewatch_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tv",
            name="rewatch_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
