from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r"^calendar/?$", views.CalendarView.as_view(), name="api_calendar"),
    re_path(
        r"^calendar/update/?$",
        views.CalendarUpdateView.as_view(),
        name="api_update_calendar",
    ),
    re_path(
        r"^history/(?P<media_type>[^/]+)/(?P<history_id>[^/]+)/?$",
        views.MediaTypeHistoryDetailView.as_view(),
        name="api_media_history_detail",
    ),
    re_path(r"^lists/?$", views.ListsView.as_view(), name="api_lists"),
    re_path(
        r"^lists/(?P<list_id>\d+)/?$",
        views.ListDetailView.as_view(),
        name="api_list_detail",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/items/?$",
        views.ListAddItemView.as_view(),
        name="api_list_add_item",
    ),
    re_path(
        r"^lists/(?P<list_id>\d+)/items/(?P<item_id>\d+)/?$",
        views.ListRemoveItemView.as_view(),
        name="api_list_remove_item",
    ),
    re_path(r"^media/?$", views.MediaListView.as_view(), name="api_media_list"),
    re_path(
        r"^media/(?P<media_type>[^/]+)/?$",
        views.MediaTypeListView.as_view(),
        name="api_media_type_list",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/?$",
        views.MediaDetailView.as_view(),
        name="api_media_detail",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/history/?$",
        views.MediaHistoryView.as_view(),
        name="api_media_history",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/lists/?$",
        views.MediaAddToListView.as_view(),
        name="api_media_add_to_list",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/recommendations/?$",
        views.MediaRecommendationsView.as_view(),
        name="api_media_recommendations",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/seasons/?$",
        views.MediaSeasonsView.as_view(),
        name="api_media_seasons",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/sync/?$",
        views.MediaSyncView.as_view(),
        name="api_media_sync",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/?$",
        views.MediaSeasonDetailView.as_view(),
        name="api_media_season_detail",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/episodes/?$",
        views.MediaSeasonEpisodesView.as_view(),
        name="api_media_season_episodes",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/history/?$",
        views.MediaSeasonHistoryView.as_view(),
        name="api_media_season_history",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/sync/?$",
        views.MediaSeasonSyncView.as_view(),
        name="api_media_season_sync",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/(?P<episode_number>\d+)/?$",
        views.MediaEpisodeDetailView.as_view(),
        name="api_media_episode_detail",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/(?P<episode_number>\d+)/history/?$",
        views.MediaEpisodeHistoryView.as_view(),
        name="api_media_episode_history",
    ),
    re_path(
        r"^media/(?P<media_type>[^/]+)/(?P<source>[^/]+)/(?P<media_id>\d+)/(?P<season_number>\d+)/(?P<episode_number>\d+)/sync/?$",
        views.MediaEpisodeSyncView.as_view(),
        name="api_media_episode_sync",
    ),
    re_path(
        r"^search/(?P<media_type>[^/]+)/?$",
        views.SearchProviderView.as_view(),
        name="api_search_provider",
    ),
    re_path(r"^statistics/?$", views.StatisticsView.as_view(), name="api_statistics"),
]
